services:
  - type: web
    runtime: docker
    name: steel-browser
    dockerfilePath: ./Dockerfile
    healthCheckPath: /v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DOMAIN
        value: "<change me to your render domain>"
      - key: USE_SSL
        value: "true"
    disk:
      name: cache
      mountPath: /app/.cache
      sizeGB: 1
